local/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

from . import settings

urlpatterns = [
    path('', RedirectView.as_view(url='/shopapp/', permanent=True)),
    path('shopapp/', include('shopapp.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopapp/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'shopapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('update_user/', views.edit_profile, name='update_user'),
    path('delete_user/', views.delete_profile, name='delete_user'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/create/', views.create_post, name='create_post'),
    path('post/<int:pk>/edit/', views.edit_post, name='edit_post'),
    path('post/<int:pk>/delete/', views.delete_post, name='delete_post'),
    path('post/<int:pk>/like/', views.like_post, name='like_post'),
    path('comment/edit/<int:pk>/', views.edit_comment, name='edit_comment'),
    path('comment/delete/<int:pk>/', views.delete_comment, name='delete_comment'),


]

shopapp/models.py
import datetime
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model

class CustomUser(AbstractUser):
    last_name = models.CharField(max_length=254, verbose_name="Фамилия")
    first_name = models.CharField(max_length=254, verbose_name="Имя")
    email = models.EmailField(max_length=254, verbose_name="Почта", unique=True)
    username = models.CharField(max_length=254, verbose_name="Логин", unique=True)
    password = models.CharField(max_length=254, verbose_name="Пароль")
    avatar = models.ImageField(upload_to="polls/user", verbose_name="Фото профиля")
    USERNAME_FIELD = 'username'

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Post(models.Model):
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name="Автор", related_name='posts')
    title = models.CharField(max_length=255, verbose_name="Заголовок")
    content = models.TextField(verbose_name="Содержимое поста")
    created_at = models.DateTimeField(default=timezone.now, verbose_name="Дата и время публикации")
    likes = models.ManyToManyField(get_user_model(), related_name='liked_posts', blank=True, verbose_name="Лайки")

    def __str__(self):
        return self.title

    def comment_count(self):
        return self.comments.count()

    def get_likes_count(self):
        return self.likes.count()

class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE, verbose_name="Пост")
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name="Автор комментария")
    content = models.TextField(verbose_name="Текст комментария")
    created_at = models.DateTimeField(default=timezone.now, verbose_name="Дата и время комментария")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Дата и время обновления комментария")

    def __str__(self):
        return f"Комментарий от {self.author} на пост {self.post}"

class Like(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post_likes')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user} лайкнул {self.post}"

    class Meta:
        unique_together = ('post', 'user')

shopapp/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django import forms
from .models import Post, Comment, CustomUser
from django.forms.models import inlineformset_factory

class RegisterForm(forms.ModelForm):
    password = forms.CharField(
        label="Пароль",
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )
    password2 = forms.CharField(
        label="Повтор пароля",
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )
    bio = forms.CharField(
        label="Биография",
        widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
        required=False
    )

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    def clean(self):
        cleaned_data = super().clean()
        pwd1 = cleaned_data.get("password")
        pwd2 = cleaned_data.get("password2")
        if pwd1 and pwd2 and pwd1 != pwd2:
            raise ValidationError({"password2": "Пароли должны совпадать"})

    class Meta:
        model = CustomUser
        fields = ("avatar", "first_name", "last_name", "username", "email", "bio")
        widgets = {
            'avatar': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
        }
class UserLoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите логин'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Введите пароль'}))

class UpdateForm(forms.ModelForm):
    avatar = forms.ImageField(label="Фото профиля", required=False)
    last_name = forms.CharField(label="Фамилия", required=False)
    first_name = forms.CharField(label="Имя", required=False)
    email = forms.CharField(label="Почта", required=False)
    username = forms.CharField(label="Логин", required=False)

    class Meta:
        model = CustomUser
        fields = ("avatar", "last_name","first_name", "email","username")

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите заголовок'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Введите текст поста', 'rows': 4}),
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Напишите комментарий', 'rows': 3}),
        }

shopapp/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import RegisterForm as UserRegistrationForm, UpdateForm as UserProfileForm, PostForm, CommentForm
from .models import CustomUser as User, Post, Like, Comment
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.core.paginator import Paginator

def index(request):
    posts_list = Post.objects.all().order_by('-created_at')
    paginator = Paginator(posts_list, 50)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'index.html', {'posts': page_obj})

@login_required
def profile(request):
    user = request.user
    user_posts = Post.objects.filter(author=user).order_by('-created_at')
    paginator = Paginator(user_posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'profile.html', {
        'user': user,
        'posts': page_obj
    })


@login_required
def edit_profile(request):
    user = request.user
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Профиль успешно обновлён.')
            return redirect('shopapp:profile')
    else:
        form = UserProfileForm(instance=user)

    return render(request, 'user_form.html', {'form': form})


@login_required
def delete_profile(request):
    user = request.user
    if request.method == 'POST':
        user.delete()
        messages.success(request, 'Ваш профиль был удалён.')
        return redirect('shopapp:index')

    return render(request, 'delete_confirm_delete.html')


def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, 'Вы успешно зарегистрировались.')
            return redirect('shopapp:profile')
    else:
        form = UserRegistrationForm()

    return render(request, 'registration/register.html', {'form': form})


def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, 'Вы успешно вошли в систему.')
                return redirect('shopapp:profile')
            else:
                messages.error(request, 'Неправильное имя пользователя или пароль.')
    else:
        form = UserLoginForm()

    return render(request, 'registration/login.html', {'form': form})


@login_required
def user_logout(request):
    logout(request)
    messages.success(request, 'Вы успешно вышли из системы.')
    return redirect('shopapp:index')

def post_list(request):
    posts = Post.objects.all().order_by('-created_at')
    paginator = Paginator(posts, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'post_list.html', {'posts': page_obj})


def like_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.likes.add(request.user)
    return redirect('shopapp:post_detail', pk=pk)


def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('shopapp:index')
    else:
        form = PostForm()
    return render(request, 'create_post.html', {'form': form})

def edit_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if post.author != request.user:
        return redirect('shopapp:index')

    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            messages.success(request, 'Пост был успешно обновлён.')
            return redirect('shopapp:post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)

    return render(request, 'edit_post.html', {'form': form, 'post': post})



def delete_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if post.author != request.user:
        return redirect('shopapp:index')

    if request.method == 'POST':
        post.delete()
        messages.success(request, 'Пост был успешно удален.')
        return redirect('shopapp:index')

    return render(request, 'delete_post.html', {'post': post})


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    comments = post.comments.all()
    comment_form = CommentForm()
    if request.method == 'POST':
        # Если отправлен комментарий
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()
            return redirect('shopapp:post_detail', pk=post.pk)
    return render(request, 'post_detail.html', {'post': post, 'comments': comments, 'comment_form': comment_form})


def edit_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)

    if comment.author != request.user:
        return redirect('shopapp:post_detail', pk=comment.post.pk)

    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            form.save()
            return redirect('shopapp:post_detail', pk=comment.post.pk)
    else:
        form = CommentForm(instance=comment)

    return render(request, 'edit_comment.html', {'form': form, 'comment': comment})

def delete_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)

    if comment.author == request.user:
        post_pk = comment.post.pk
        comment.delete()
        return redirect('shopapp:post_detail', pk=post_pk)
    else:
        return redirect('shopapp:post_detail', pk=comment.post.pk)

shopapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Главная страница{% endblock %}</title>
    <!-- Bootstrap 5 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">

</head>
<body>
    <header class="bg-light p-3 mb-4">
        <div class="container">
            <h1><a class="text-decoration-none" href="{% url 'shopapp:index' %}">Главная</a></h1>
            <nav>
                {% if user.is_authenticated %}
                    <a class="btn btn-outline-primary btn-sm me-2" href="{% url 'shopapp:create_post' %}">Создать пост</a>
                    <a class="btn btn-outline-primary btn-sm me-2" href="{% url 'shopapp:profile' %}">Профиль</a>
                    <a class="btn btn-outline-secondary btn-sm me-2" href="{% url 'shopapp:logout' %}">Выход</a>
                {% else %}
                    <a class="btn btn-outline-primary btn-sm me-2" href="{% url 'shopapp:register' %}">Регистрация</a>
                    <a class="btn btn-outline-secondary btn-sm" href="{% url 'shopapp:login' %}">Вход</a>
                {% endif %}
            </nav>
        </div>
    </header>

    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

shopapp/templates/create_post.html
{% extends 'base.html' %}

{% block title %}Создание поста{% endblock %}

{% block content %}
  <h2 class="mb-4">Создание поста</h2>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-primary w-100" type="submit">Создать пост</button>
  </form>
{% endblock %}

shopapp/templates/delete_post.html
{% extends 'base.html' %}

{% block title %}Удалить пост{% endblock %}

{% block content %}
    <h2>Точно удалить?"{{ post.title }}"?</h2>
    <form method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Удалить</button>
        <a href="{% url 'shopapp:post_detail' post.pk %}" class="btn btn-secondary">Отмена</a>
    </form>
{% endblock %}

shopapp/templates/edit_comment.html
{% extends 'base.html' %}

{% block title %}Изменить комментарий{% endblock %}

{% block content %}
<h2>Редактировать комментарий</h2>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-success w-50" type="submit">Сохранить изменения</button>
</form>

<a href="{% url 'shopapp:post_detail' comment.post.pk %}">Назад к посту</a>
{% endblock %}

shopapp/templates/edit_post.html
{% extends 'base.html' %}

{% block title %}Редактировать пост{% endblock %}

{% block content %}
    <h2>Редактировать пост</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success w-30">Сохранить изменения</button>
        <a href="{% url 'shopapp:post_detail' post.pk %}" class="btn btn-secondary w-30">Отмена</a>
    </form>
{% endblock %}

shopapp/templates/index.html
{% extends 'base.html' %}

{% block title %}Главная страница{% endblock %}

{% block content %}
  <div class="text-center">
    <h1 class="display-4">Добро пожаловать на наш сайт</h1>
  </div>

<h2 class="mb-4">Все посты</h2>

{% for post in posts %}
    <div class="card mb-3">
        <div class="card-body">
            <h5 class="card-title">{{ post.title }}</h5>
            <p class="card-text">{{ post.content|truncatewords:20 }}</p>
            <p class="text-muted">
                Автор: {{ post.author }} | Дата публикации: {{ post.created_at }} | Комментариев: {{ post.comments.count }}
            </p>
            <a href="{% url 'shopapp:post_detail' post.pk %}" class="btn btn-primary">Читать далее</a>
        </div>
    </div>
{% endfor %}

<div class="mt-4">
    <nav aria-label="Пагинация">
        <ul class="pagination justify-content-center">
            {% if posts.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ posts.previous_page_number }}">Предыдущая</a>
                </li>
            {% endif %}

            <li class="page-item disabled">
                <span class="page-link">Страница {{ posts.number }} из {{ posts.paginator.num_pages }}</span>
            </li>

            {% if posts.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ posts.next_page_number }}">Следующая</a>
                </li>
            {% endif %}
        </ul>
    </nav>
</div>

{% endblock %}

shopapp/templates/post_detail.html
{% extends 'base.html' %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
<h2>{{ post.title }}</h2>
<p class="text-muted">
    Автор: {{ post.author }} | Дата публикации: {{ post.created_at }}
</p>
<p>{{ post.content }}</p>

<form method="POST" action="{% url 'shopapp:like_post' post.pk %}">
    {% csrf_token %}
    <button type="submit" class="btn btn-outline-primary">
        ❤ Лайков: {{ post.likes.count }}
    </button>
</form>
{% if post.author == user %}
    <div class="my-3">
        <a href="{% url 'shopapp:edit_post' post.pk %}" class="btn btn-warning btn-sm">&#9997; Редактировать</a>
        <a href="{% url 'shopapp:delete_post' post.pk %}" class="btn btn-danger btn-sm">&#128465; Удалить</a>
    </div>
{% endif %}

<hr>

<h3>Комментарии</h3>

{% for comment in comments %}
    <div class="comment mb-3">
        <p><strong>{{ comment.author }}</strong> ({{ comment.created_at }})</p>
        <p>{{ comment.content }}</p>

        {% if comment.author == user %}
            <a href="{% url 'shopapp:edit_comment' comment.pk %}">Редактировать</a> |
            <a href="{% url 'shopapp:delete_comment' comment.pk %}">Удалить</a>
        {% endif %}
    </div>
{% empty %}
    <p>Комментариев пока нет.</p>
{% endfor %}

<h4>Оставить комментарий</h4>
 {% if user.is_authenticated %}
<form method="POST">
    {% csrf_token %}
    {{ comment_form.as_p }}
    <button type="submit" class="btn btn-success mb-4">Оставить комментарий</button>
</form>
 {% else %}
    <p>Вам нужно авторизоваться чтобы писать комментарии</p>
 {% endif %}
{% endblock %}

shopapp/templates/profile.html
{% extends 'base.html' %}

{% block title %}Профиль{% endblock %}

{% block content %}
<div class="profile">
  <h1>Пользователь: {{ user.username }}</h1>
  <p><strong>Фамилия:</strong> {{ user.last_name }}</p>
  <p><strong>Имя:</strong> {{ user.first_name }}</p>
  <p><strong>Почта:</strong> {{ user.email }}</p>

  {% if user.avatar %}
    <img src="{{ user.avatar.url }}" alt="Аватар" class="img-thumbnail" style="max-width: 200px;">
  {% endif %}

  <div class="mt-3">
    <a href="{% url 'shopapp:update_user' %}" class="btn btn-outline-primary">Изменить профиль</a>
    <a href="{% url 'shopapp:delete_user' %}" class="btn btn-outline-danger">Удалить профиль</a>
  </div>
</div>

<hr>

<h2>Посты пользователя ({{ user.posts.count }})</h2>

{% for post in posts %}
  <div class="card mb-3">
    <div class="card-body">
      <h5 class="card-title">{{ post.title }}</h5>
      <p class="card-text">{{ post.content|truncatewords:20 }}</p>
      <p class="text-muted">
        Дата публикации: {{ post.created_at }}
        | Комментариев: {{ post.comments.count }}
        | Лайков: {{ post.likes.count }}
      </p>
      <a href="{% url 'shopapp:post_detail' post.pk %}" class="btn btn-sm btn-primary">Читать далее</a>
    </div>
  </div>
{% empty %}
  <p>У пользователя пока нет постов.</p>
{% endfor %}

<nav aria-label="Пагинация профиля">
  <ul class="pagination justify-content-center">
    {% if posts.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ posts.previous_page_number }}">Предыдущая</a>
      </li>
    {% endif %}

    <li class="page-item disabled">
      <span class="page-link">Стр. {{ posts.number }} из {{ posts.paginator.num_pages }}</span>
    </li>

    {% if posts.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ posts.next_page_number }}">Следующая</a>
      </li>
    {% endif %}
  </ul>
</nav>

{% endblock %}

shopapp/templates/user_confirm_delete.html
{% extends 'base.html' %}
{% block content %}

  <h2>Удаление профиля</h2>
  <span>Вы уверены?</span>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Да</button>
  </form>

{% endblock %}

shopapp/templates/user_form.html
{% extends 'base.html' %}
{% block content %}

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit">Изменить</button>
    </form>

{% endblock %}